### ISSUE TITLE
Where is this file PromptPulse_1_0_0_0.zip

### ISSUE THREAD

**Issue by otsindra** [pnp/prompt-pulse#1]
Hello,

I was following your instructions to get started and noticed that this file link is missing - PromptPulse_1_0_0_0.zip. 

Please point to the correct download link.

**Comment by alexc-MSFT** [comment]
@otsindra I'm very pleased to see you are interested in this. We are still populating this repository as it hasn't been released yet.

I hope to have the file uploaded and the solution properly released tomorrow.

Thanks

**Comment by alexc-MSFT** [comment]
@otsindra prompt pulse has now been released so you will find the solution file there. Thanks
