### ISSUE TITLE
Updating new release

### ISSUE THREAD

**Issue by carolinacadenas** [pnp/prompt-pulse#21]
I have tried to update the new version version via importing the new solution and I getting these errors:
![image](https://github.com/user-attachments/assets/12cc9b6a-fceb-472b-8e5c-1795cc0f786b)
![image](https://github.com/user-attachments/assets/ca49c425-2124-4f17-b616-4656196057bb)

Could you please advise if this is the correct approach as I can't find any guidance in your documentation.

**Comment by alexc-MSFT** [comment]
@carolinacadenas thanks for spotting this, I have just re-released v2.1.0.0 with a fix (please re-download). Looks like there were some incorrect dependencies which I have removed.

And yes you are importing/upgrading it in the correct way.

Will close the issue, please reopen if you still have trouble.
