### ISSUE TITLE
Options are not visible after updating to new app version

### ISSUE THREAD

**Issue by carolinacadenas** [pnp/prompt-pulse#23]
After updating the app to new release, I don't see all the options:

![New release](https://github.com/user-attachments/assets/b2ed0022-8046-484d-b4aa-8e88a9084951)

I tried to make them visible but the button is greyed-on.

Any ideas on how to resolve this?

**Comment by alexc-MSFT** [comment]
@carolinacadenas sorry there are some additional steps in the deployment guide, specifically a new list (Reporting) and also some new list items to create in the 'Configuration' list, these determine whether to show/hide the Engage and Users drop downs.

Please follow those steps and you sghould be fine.

Thanks

**Comment by carolinacadenas** [comment]
Thank you @alexc-MSFT. This is working now.

**Comment by alexc-MSFT** [comment]
Excellent glad to hear it @carolinacadenas - closing the issue.
